
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, "8.0"
inhibit_all_warnings!
use_frameworks!


target 'MFWebKit_Example' do
    pod "MFWebKit", :path => "../"
end



#use_frameworks!
#
#target 'MFWebKit_Example' do
#  pod 'MFWebKit', :path => '../'
#
#  target 'MFWebKit_Tests' do
#    inherit! :search_paths
#
#
#  end
#end
