#!/bin/sh
#更改了podspec中的版本号，需要pod install，之后再执行脚本
echo "更改了podspec中的版本号，需要pod install，之后再执行脚本"

echo -n "enter the version : "
read version 

echo "**************begin commit*********************"
git add -A && git commit -m "Release ${version}"

echo "***************begin tag***********************"
git tag ${version}

echo "**************begin push -tags*****************"
git push --tags

echo "**************begin push origin****************"
git push origin master

echo "**************begin trunk push*****************"
pod trunk push MFWebKit.podspec --verbose --allow-warnings
